### ISSUE TITLE
onSelected is not a function

### ISSUE THREAD

**Issue by gregbia** [StevenIseki/react-giphy-picker#4]
Great component!

The Giphy select list is showing but when I select a GIF I get:

`Uncaught TypeError: n.props.onSelected is not a function`

I'm simply trying: 

`<Picker onSelected={ console.log(this) } />`

**Comment by StevenIseki** [comment]
I think you have to use bind for the function e.g. 


```
class TestComponent extends Component {
  log (gif) {
    console.log(gif)
  }

  render () {
    return (
      <div>
        <Picker onSelected={this.log.bind(this)} />
      </div>
    )
  }
}
```
